### ISSUE TITLE
err (-22) on device initialization

### ISSUE THREAD

**Issue by andyandroid** [OpenChannelSSD/lnvm#3]
When Instantiate with the null_blk driver, I hit err (-22), I am not sure it is a err of lnvm, 

> andy@andy-MS-7758:~$ sudo modprobe null_blk use_lightnvm=1 gb=4
> andy@andy-MS-7758:~$ dmesg |grep nvm
> [ 1309.903873] nvm: registered nullb0 [1/1/256/4096/1/1]
> [ 1309.903887] nvm: err (-22) on device initialization
> [ 1309.903965] nvm: registered nullb1 [1/1/256/4096/1/1]
> [ 1309.903978] nvm: err (-22) on device initialization

When Instantiate media manager and target with the cmd, the cmd fail and the dmesg show device has no media manager registered

> sudo lnvm create -d nullb0 -n mydevice -t rrpc
> [ 3781.568705] nvm: device has no media manager registered.

Below are basic Linux and kernel info
lnvm version: 1.0

> andy@andy-MS-7758:~$ lsb_release -a
> No LSB modules are available.
> Distributor ID: Ubuntu
> Description:    Ubuntu 16.04 LTS
> Release:    16.04
> Codename:   xenial
> andy@andy-MS-7758:~$ uname -a
> Linux andy-MS-7758 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MatiasBjorling** [comment]
Hi Andy,

Does it help if you do 

  sudo modprobe gennvm 

and then try again to initialize the target?

**Comment by andyandroid** [comment]
Hi Matias

I have the same result.

> andy@andy-MS-7758:~$ sudo modprobe gennvm
> [sudo] andy 的密码： 
> andy@andy-MS-7758:~$ sudo modprobe null_blk use_lightnvm=1 gb=4
> andy@andy-MS-7758:~$ dmesg |grep nvm
> [  229.331590] nvm: registered nullb0 [1/1/256/4096/1/1]
> [  229.331603] nvm: err (-22) on device initialization
> [  229.331674] nvm: registered nullb1 [1/1/256/4096/1/1]
> [  229.331682] nvm: err (-22) on device initialization

**Comment by MatiasBjorling** [comment]
Hmm, there might be missing a patch for lightnvm that was fixed in the 4.6 cycle.

Could you try installing the latest kernel for ubuntu and see if the problem persist? 

http://www.yourownlinux.com/2016/05/how-to-install-linux-kernel-4-6-rc6-in-linux.html

**Comment by andyandroid** [comment]
Matias

No err after installing latest kernel, Thanks a lot.

**Comment by MatiasBjorling** [comment]
Thanks for testing it.
