### ISSUE TITLE
Can lnvm create two or more OCSSDs into one pblk?

### ISSUE THREAD

**Issue by trevery** [OpenChannelSSD/lnvm#5]
I have two 512GB OCSSD devices. Both of them are able to use lnvm command to create pblk. But I need to combine these two physical 512GB devices into one  logic 1TB devices without changing File System. It seems that the command 'create' cann't not make it, because it can only create one device at a time. Is there any idea about how to make it?

**Comment by MatiasBjorling** [comment]
Hi,

It is not possible to combine the drives at the pblk level. You'll have to put dm-linear or dm raid on top to combine to a single block device.
